name: automated_testing_framework
description: A testing framework that allows in app tests to be built and executed in an automated way.
version: 1.2.17+4
homepage: https://github.com/peiffer-innovations/automated_testing_framework

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  child_builder: ^1.0.0+2
  convert: ^2.1.1
  device_info: ">=0.4.2+7 <2.0.0"
  flutter:
    sdk: flutter
  form_validation: ^1.0.1
  intl: ^0.16.1
  json_class: ^1.0.6+1
  json_theme: ^1.3.3+1
  logging: ^0.11.4
  meta: ^1.1.8
  package_info: ">=0.4.3 <2.0.0"
  pointycastle: ^2.0.0
  provider: ^4.3.2+2
  static_translations: ^1.0.3
  tinycolor: ^1.0.2
  uuid: ^2.2.2
  websafe_platform: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
