name: automated_testing_framework
description: A testing framework that allows in app tests to be built and executed in an automated way.
version: 3.2.1
homepage: https://github.com/peiffer-innovations/automated_testing_framework

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  automated_testing_framework_models: ^2.0.8+1
  child_builder: ^2.0.0+2
  convert: ^3.0.1
  device_info: ^2.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.6
  form_validation: ^2.1.0+1
  intl: ^0.17.0
  json_class: ^2.1.2+3
  json_theme: ^3.2.4
  logging: ^1.0.2
  meta: ^1.7.0
  package_info_plus: ^1.0.6
  provider: ^6.0.0
  static_translations: ^2.1.0+1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

