name: automated_testing_framework
description: A testing framework that allows in app tests to be built and executed in an automated way.
version: 4.0.1
homepage: https://github.com/peiffer-innovations/automated_testing_framework

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  automated_testing_framework_models: ^2.0.9
  child_builder: ^2.0.0+3
  convert: ^3.0.1
  device_info_plus: ^3.2.3
  device_info_plus_web: ^2.1.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_web_plugins:
    sdk: flutter
  form_validation: ^2.1.0+2
  intl: ^0.17.0
  json_class: ^2.1.2+4
  json_theme: ^4.0.0
  logging: ^1.0.2
  meta: ^1.7.0
  package_info_plus: ^1.4.2
  package_info_plus_web: ^1.0.5
  provider: ^6.0.2
  static_translations: ^2.1.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

